### ISSUE TITLE
Very great work! Would you please provide the code of Orchestra under local-DP based clustering method (chang et al. 2021)?

### ISSUE THREAD

**Issue by liyuntong9** [akhilmathurs/orchestra#1]

**Comment by EkdeepSLubana** [comment]
Thank you for your interest in our work! 

While we implemented almost everything from scratch in our codebase, the local-DP experiment you're referring to was conducted at the very end and was based on a hard-coded integration of Google's LSH based Local-DP clustering code: https://github.com/google/differential-privacy/tree/main/learning/clustering

Essentially, we directly ran their code by calling it within Orchestra's local clustering step (see image below). Cleaning up the messy integration will need some time and I can try that over the next few weeks. If you'd prefer to take a jab, please go ahead and feel free to make a pull request.

<img width="695" alt="local-DP" src="https://user-images.githubusercontent.com/16430942/172964803-4cfadf3d-d73c-493b-89b7-337e12f96c65.png">

**Comment by liyuntong9** [comment]
Thank you! Looking forward to the new version. It will help me a lot.
